version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    ports:
      - "8000:80"  # Maps port 8000 on the host to port 80 in the container
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=movie
      - DB_USERNAME=root
      - DB_PASSWORD=root
    command: >
      bash -c "composer install && php artisan migrate --force && apache2-foreground"

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: movie
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql 

volumes:
  db_data:
