version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        ports:
            - "80:80"
        depends_on:
            - db
            - fluentd
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=movie
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - API_KEY=3f1deceb
            - FLUENTD_HOST=fluentd
            - FLUENTD_PORT=24224
            - TZ=Asia/Tokyo
        command: >
            bash -c "sleep 40 && composer install && php artisan migrate --force && php artisan key:generate && apache2-foreground"
        logging:
            driver: fluentd
            options:
                fluentd-address: fluentd:24224
                tag: docker.{{.Name}}
                fluentd-async-connect: "true"
        volumes:
            - app_logs:/var/www/html/storage/logs
        networks:
            - app-network

    db:
        image: mysql:latest
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: movie
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

    fluentd:
        build:
            context: ./fluentd
            dockerfile: Dockerfile
        container_name: fluentd
        volumes:
            - ./fluentd/conf:/fluentd/etc
            - app_logs:/fluentd/logs
        ports:
            - "24224:24224"
            - "24224:24224/udp"
        command: fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins
        environment:
            - FLUENTD_CONF=fluent.conf
            - TZ=Asia/Tokyo
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
    app_logs:
